# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MVVM_TestApp' do

    pod 'Mantle', '~> 1.5.3'
    pod "AFNetworking", "~> 2.0"
    pod 'KVOController'
    
end

target 'MVVM_TestAppTests' do

end

